/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author moham
 */
package hotel.management.system;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


public class Services extends javax.swing.JFrame {
    private String role;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Services.class.getName());

    /**
     * Creates new form Services
     */
    public Services() {
        this(null);
    }

    public Services(String role) {
        initComponents();
        this.role = role;
        loadServicesFromFile();
        setupSearchPlaceholder(jTextField1, "Search services...");
    }

    /** Clears placeholder text on mouse enter, restores it on mouse exit. */
    private void setupSearchPlaceholder(javax.swing.JTextField field, String placeholder) {
        field.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(java.awt.Color.BLACK);
                }
            }
            @Override public void mouseExited(java.awt.event.MouseEvent e) {
                if (field.getText().trim().isEmpty()) {
                    field.setForeground(java.awt.Color.GRAY);
                    field.setText(placeholder);
                }
            }
        });
    }

    private void loadServicesFromFile() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        try (BufferedReader br = new BufferedReader(new FileReader("services.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length >= 4) { 
                    model.addRow(data);
                }
            }
        } catch (IOException e) {
        }
    }
private void loadReservations() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    try (BufferedReader br = new BufferedReader(new FileReader("reservations.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            model.addRow(line.split(","));
        }
    } catch (IOException e) {
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(250, 249, 246));
        jTable1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Service Name", "Category", "Description", "price", "Available", "Used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(250, 249, 246));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1080, 300));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 200, 90, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, 90, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Service");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, 50));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Available");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/serv4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1200, 510));

        jTextField1.setText("Search services...");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 450, 30));

        jPanel1.setBackground(new java.awt.Color(139, 115, 91));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(1122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);

            try (BufferedWriter bw = new BufferedWriter(new FileWriter("services.txt"))) {
                for (int i = 0; i < model.getRowCount(); i++) {
                    StringBuilder line = new StringBuilder();
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        line.append(model.getValueAt(i, j).toString());
                        if (j < model.getColumnCount() - 1) line.append(",");
                    }
                    bw.write(line.toString());
                    bw.newLine();
                }
                JOptionPane.showMessageDialog(this, "Service deleted successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error updating file!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a service from the table to delete!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String name = JOptionPane.showInputDialog(this, "Enter Service Name:");
    if (name == null || name.isEmpty()) return;

    String category = JOptionPane.showInputDialog(this, "Enter Category:");
    String description = JOptionPane.showInputDialog(this, "Enter Description:");
    String price = JOptionPane.showInputDialog(this, "Enter Price:");
    String available = "Yes"; 
    String used = "0";    

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{name, category, description, price, available, used});

    try (BufferedWriter bw = new BufferedWriter(new FileWriter("services.txt", true))) {
        bw.write(name + "," + category + "," + description + "," + price + "," + available + "," + used);
        bw.newLine();
        JOptionPane.showMessageDialog(this, "Service Added Successfully!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving to file!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int selectedRow = jTable1.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a service first!");
    return;
}

int modelRow = jTable1.convertRowIndexToModel(selectedRow);
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// Pre-fill with current values so user sees what they are editing
String name        = JOptionPane.showInputDialog(this, "Enter Service Name:",  model.getValueAt(modelRow, 0));
if (name == null || name.isEmpty()) return;
String category    = JOptionPane.showInputDialog(this, "Enter Category:",      model.getValueAt(modelRow, 1));
String description = JOptionPane.showInputDialog(this, "Enter Description:",   model.getValueAt(modelRow, 2));
String price       = JOptionPane.showInputDialog(this, "Enter Price:",         model.getValueAt(modelRow, 3));
String used        = JOptionPane.showInputDialog(this, "Used:",                model.getValueAt(modelRow, 5));

// UPDATE the existing row — not add a new one
model.setValueAt(name,        modelRow, 0);
model.setValueAt(category,    modelRow, 1);
model.setValueAt(description, modelRow, 2);
model.setValueAt(price,       modelRow, 3);
model.setValueAt(used,        modelRow, 5);

// Save all rows back to file
try (BufferedWriter bw = new BufferedWriter(new FileWriter("services.txt"))) {
    for (int i = 0; i < model.getRowCount(); i++) {
        StringBuilder line = new StringBuilder();
        for (int j = 0; j < model.getColumnCount(); j++) {
            Object val = model.getValueAt(i, j);
            line.append(val != null ? val.toString() : "");
            if (j < model.getColumnCount() - 1) line.append(",");
        }
        bw.write(line.toString());
        bw.newLine();
    }
    JOptionPane.showMessageDialog(this, "Service Edited Successfully!");
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error saving to file!");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRow = jTable1.getSelectedRow(); 

    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String currentStatus = model.getValueAt(selectedRow, 4).toString();
        String newStatus;
        if (currentStatus.equalsIgnoreCase("Yes")) {
            newStatus = "No";
        } else {
            newStatus = "Yes";
        }
        model.setValueAt(newStatus, selectedRow, 4);


        try (BufferedWriter bw = new BufferedWriter(new FileWriter("services.txt"))) {
            for (int i = 0; i < model.getRowCount(); i++) {
                StringBuilder line = new StringBuilder();
                for (int j = 0; j < model.getColumnCount(); j++) {
                    Object value = model.getValueAt(i, j);
                    line.append(value != null ? value.toString() : "");
                    if (j < model.getColumnCount() - 1) line.append(",");
                }
                bw.write(line.toString());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(this, "Service status updated to: " + newStatus);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error updating file: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a service from the table first!");
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    if ("receptionist".equalsIgnoreCase(role)) {
        new Home1("Receptionist").setVisible(true);
    } else {
        new Home1(role).setVisible(true);
    }
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Services().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void saveAllToFile() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
